fetch unshallow optional

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -64,6 +64,12 @@ runs:
         MAJOR_VERSION_BRANCH="${MAJOR_VERSION_BRANCH%%.*}"
         echo "Major version: ${MAJOR_VERSION_BRANCH}"
         
+        # TODO: I don't think this fetch should be required with the right
+        # params for action/checkout but so far have not been able to get it
+        # to work.
+        # if checked out with 'fetch-depth: 0', this will fail
+        git fetch --prune --unshallow --all || true
+        
         if git show-ref --verify --quiet "refs/heads/${MAJOR_VERSION_BRANCH}"; then
           git checkout "${MAJOR_VERSION_BRANCH}"
           git merge --ff-only main
